// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PDVStore.Data;

namespace PDVStore.Migrations
{
    [DbContext(typeof(PDVContext))]
    partial class PDVContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            modelBuilder.Entity("PDVStore.Models.UsuarioCaixa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("UsuarioCaixa");

                    b.HasData(new
                    {
                        Id = 1,
                        Nome = "Admin",
                        Email = "admin@pdvstore.local",
                        SenhaHash = "$2a$11$abcdefghijklmnopqrstuv",
                        CreatedAt = new DateTime(2026, 7, 3, 0, 0, 0, DateTimeKind.Utc)
                    });
                });
        }
    }
}
